config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :banners
  end
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file :attachment,
                :url  => "/assets/banners/:id/:style_:basename.:extension",
                :path => ":rails_root/public/assets/banners/:id/:style_:basename.:extension"

  validates_attachment_presence :attachment
  validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg', 'image/x-png', 'image/pjpeg']
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::ResourceController
  def index

  end

end

app/views/admin/banners/_form.html.erb
<fieldset>
    <%= f.field_container :min do %>
      <%= f.label :attachment %><br />
      <%= f.file_field :attachment %>
    <% end %>
</fieldset>

app/views/admin/banners/edit.html.erb
<h1><%= t("edit_banner")%></h1>
<%= form_for [:admin, @banner] do |f| %>
<%= render "shared/error_messages", :target => @banner %>
<%= render "form", :f => f %>
<%= render :partial => "admin/shared/edit_resource_links" %>

<% end %>

app/views/admin/banners/index.html.erb
<div class="toolbar">
  <ul class="actions">
    <li id="new_banner_link">
      <%= link_to new_admin_banner_url, :class => "button", :id => "admin_new_banner" do %>
        <span><%= image_tag "/images/admin/icons/add.png", :alt => "Add" %> <%= t("new_banner") %></span>
      <% end %>
    </li>
  </ul>
  <br class="clear">
</div>
<h1><%= t("listing_banners") %></h1>
<table class="index" id='listing_banners'>
  <thead>
    <tr>
      <%= hook :admin_banners do %>
        <th><%= t("activerecord.attributes.banner.attachment_file_name") %></th>
        <th><%= t("activerecord.attributes.banner.attachment") %></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @banners.each do |banner| %>
    <tr>
      <%- locals = {:banner => banner} %>
      <%= hook :admin_banners_index_rows, locals do %>
        <td><%= banner.attachment_file_name %></td>
        <td><%= image_tag(banner.attachment.url) %></td>
        <td class="actions"><%= link_to t("delete"), admin_banner_path(banner), :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/banners/new.html.erb
<h1><%= t("new_banner")%></h1>
<%= form_for [:admin, @banner], :html => {:multipart => true} do |f| %>
<%= render "shared/error_messages", :target => @banner %>
<%= render "form", :f => f %>
<%= render :partial => "admin/shared/new_resource_links" %>

<% end %>